import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../src/worker.js';
import {createDatabase} from './db.mjs';
const origin='https://fine.test';
const quote={request_id:'a8b83c7b-5a2e-4a70-9508-cda6cd3b5237',nome:'Ana Teste',email:'ana@example.test',whatsapp:'11999999999',produto:'Projeto personalizado',quantidade:3,prazo:'7 dias',descricao:'Preciso de três peças para reposição.',website:''};
function fixture(){return {DB:createDatabase(),ADMIN_PASSWORD:'Senha-de-teste-segura!2026',ASSETS:{fetch:async()=>new Response('asset')}};}
async function req(env,path,method='GET',body,headers={}){return worker.fetch(new Request(origin+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{Origin:origin}:{}),...headers},...(body?{body:typeof body==='string'?body:JSON.stringify(body)}:{})}),env,{waitUntil(){}});}
async function login(env){const r=await req(env,'/api/login','POST',{username:'admin',password:env.ADMIN_PASSWORD});assert.equal(r.status,200);return r.headers.get('set-cookie').split(';')[0];}
test('private quotes cannot be read without login',async()=>{assert.equal((await req(fixture(),'/api/admin/quotes')).status,401);});
test('login rejects an incorrect password and limits repeated attempts',async()=>{const env=fixture();for(let i=0;i<8;i++)assert.equal((await req(env,'/api/login','POST',{username:'admin',password:'wrong'})).status,401);assert.equal((await req(env,'/api/login','POST',{username:'admin',password:'wrong'})).status,429);});
test('successful login gives HttpOnly secure cookie and logout revokes it',async()=>{const env=fixture();const res=await req(env,'/api/login','POST',{username:'admin',password:env.ADMIN_PASSWORD});assert.equal(res.status,200);const cookie=res.headers.get('set-cookie');assert.match(cookie,/HttpOnly/);assert.match(cookie,/Secure/);assert.match(cookie,/SameSite=Strict/);const header=cookie.split(';')[0];assert.equal((await req(env,'/api/admin/session','GET',null,{Cookie:header})).status,200);assert.equal((await req(env,'/api/logout','POST',{}, {Cookie:header})).status,200);assert.equal((await req(env,'/api/admin/session','GET',null,{Cookie:header})).status,401);});
test('expired session cannot read customer data',async()=>{const env=fixture();const cookie=await login(env);env.DB.sql.exec('UPDATE sessions SET expires_at=0');assert.equal((await req(env,'/api/admin/quotes','GET',null,{Cookie:cookie})).status,401);});
test('cross-origin mutation is rejected even with a valid cookie',async()=>{const env=fixture();const cookie=await login(env);assert.equal((await req(env,'/api/admin/settings','PUT',{}, {Cookie:cookie,Origin:'https://other.test'})).status,403);});
test('a quote is stored and a retry returns the same id without duplication',async()=>{const env=fixture();const r=await req(env,'/api/quotes','POST',quote);assert.equal(r.status,201);const first=await r.json();assert.equal((await req(env,'/api/quotes','POST',quote)).status,200);const cookie=await login(env);const list=await (await req(env,'/api/admin/quotes','GET',null,{Cookie:cookie})).json();assert.equal(list.quotes.length,1);assert.equal(list.quotes[0].id,first.id);assert.equal(list.quotes[0].nome,'Ana Teste');assert.equal(list.quotes[0].status,'NOVO');});
test('invalid quote, malformed JSON and honeypot are rejected without storing',async()=>{const env=fixture();assert.equal((await req(env,'/api/quotes','POST',{...quote,email:'bad'})).status,400);assert.equal((await req(env,'/api/quotes','POST','{invalid')).status,400);assert.equal((await req(env,'/api/quotes','POST',{...quote,website:'spam'})).status,400);assert.equal(env.DB.sql.prepare('SELECT COUNT(*) AS n FROM quotes').get().n,0);});
test('missing database never pretends to have received a quote',async()=>{const env=fixture();delete env.DB;assert.equal((await req(env,'/api/quotes','POST',quote)).status,503);});
test('admin can update the quote status and notes',async()=>{const env=fixture();const {id}=await (await req(env,'/api/quotes','POST',quote)).json();const cookie=await login(env);assert.equal((await req(env,'/api/admin/quotes/'+id,'PATCH',{version:1,status:'EM_ATENDIMENTO',notes:'Enviar proposta amanhã'}, {Cookie:cookie})).status,200);const list=await (await req(env,'/api/admin/quotes','GET',null,{Cookie:cookie})).json();assert.equal(list.quotes[0].status,'EM_ATENDIMENTO');assert.equal(list.quotes[0].notes,'Enviar proposta amanhã');});
test('public catalogue follows admin edits and hides inactive products',async()=>{const env=fixture();const cookie=await login(env);const site=await (await req(env,'/api/site')).json();const original=site.products[0];assert.equal((await req(env,'/api/admin/products/'+original.id,'PUT',{...original,nome:'Novo nome',active:false},{Cookie:cookie})).status,200);const updated=await (await req(env,'/api/site')).json();assert.equal(updated.products.some(p=>p.id===original.id),false);const admin=await (await req(env,'/api/admin/products','GET',null,{Cookie:cookie})).json();assert.equal(admin.products.find(p=>p.id===original.id).nome,'Novo nome');});
test('products reject javascript URLs and unsupported image data',async()=>{const env=fixture();const cookie=await login(env);const p=(await (await req(env,'/api/site')).json()).products[0];assert.equal((await req(env,'/api/admin/products/'+p.id,'PUT',{...p,links:[{l:'Comprar',u:'javascript:alert(1)'}]},{Cookie:cookie})).status,400);assert.equal((await req(env,'/api/admin/products/'+p.id,'PUT',{...p,img:'data:image/svg+xml,<svg></svg>'},{Cookie:cookie})).status,400);});
test('content updates appear publicly and stale edits do not overwrite them',async()=>{const env=fixture();const cookie=await login(env);const a=await (await req(env,'/api/admin/settings','GET',null,{Cookie:cookie})).json();assert.equal((await req(env,'/api/admin/settings','PUT',{version:a.version,settings:{...a.settings,hero_title:'Nova chamada'}},{Cookie:cookie})).status,200);const site=await (await req(env,'/api/site')).json();assert.equal(site.settings.hero_title,'Nova chamada');assert.equal((await req(env,'/api/admin/settings','PUT',{version:a.version,settings:a.settings},{Cookie:cookie})).status,409);});
test('an admin creates an attendance access that can manage orders but not site content',async()=>{const env=fixture();const cookie=await login(env);const create=await req(env,'/api/admin/users','POST',{name:'Equipe Teste',username:'equipe',password:'Equipe-segura!2026',role:'ATENDIMENTO'},{Cookie:cookie});assert.equal(create.status,201);const r=await req(env,'/api/login','POST',{username:'equipe',password:'Equipe-segura!2026'});assert.equal(r.status,200);const teamCookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await req(env,'/api/admin/quotes','GET',null,{Cookie:teamCookie})).status,200);assert.equal((await req(env,'/api/admin/settings','GET',null,{Cookie:teamCookie})).status,403);assert.equal((await req(env,'/api/admin/users','GET',null,{Cookie:teamCookie})).status,403);});
test('deactivated access loses its existing session',async()=>{const env=fixture();const admin=await login(env);const c=await req(env,'/api/admin/users','POST',{name:'Outro Admin',username:'outro',password:'Outro-seguro!2026',role:'ADMIN'},{Cookie:admin});assert.equal(c.status,201);const {user}=await c.json();const r=await req(env,'/api/login','POST',{username:'outro',password:'Outro-seguro!2026'});const cookie=r.headers.get('set-cookie').split(';')[0];assert.equal((await req(env,'/api/admin/users/'+user.id,'PATCH',{active:false},{Cookie:admin})).status,200);assert.equal((await req(env,'/api/admin/session','GET',null,{Cookie:cookie})).status,401);});
test('a quote preserves whether the client has a 3D file and moves through approved invoiced delivered',async()=>{const env=fixture();const {id}=await (await req(env,'/api/quotes','POST',{...quote,has_file:'SIM'})).json();const cookie=await login(env);let version=1;for(const status of ['APROVADO','FATURADO','ENTREGUE']){assert.equal((await req(env,'/api/admin/quotes/'+id,'PATCH',{version:version++,status,notes:'Fluxo do pedido'},{Cookie:cookie})).status,200);}const {quotes}=await (await req(env,'/api/admin/quotes','GET',null,{Cookie:cookie})).json();assert.equal(quotes[0].has_file,'SIM');assert.equal(quotes[0].status,'ENTREGUE');});
test('stale order edits cannot overwrite a newer status or notes',async()=>{const env=fixture();const {id}=await (await req(env,'/api/quotes','POST',quote)).json();const cookie=await login(env);const payload={version:1,status:'APROVADO',notes:'Aprovado por Ana'};assert.equal((await req(env,'/api/admin/quotes/'+id,'PATCH',payload,{Cookie:cookie})).status,200);assert.equal((await req(env,'/api/admin/quotes/'+id,'PATCH',{...payload,status:'NOVO',notes:'Notas antigas'},{Cookie:cookie})).status,409);const q=(await (await req(env,'/api/admin/quotes','GET',null,{Cookie:cookie})).json()).quotes[0];assert.equal(q.status,'APROVADO');assert.equal(q.notes,'Aprovado por Ana');});
test('new access preserves the exact password including surrounding spaces',async()=>{const env=fixture(),cookie=await login(env),password='  Equipe com espacos!2026  ';assert.equal((await req(env,'/api/admin/users','POST',{name:'Equipe',username:'espacos',password,role:'ATENDIMENTO'},{Cookie:cookie})).status,201);assert.equal((await req(env,'/api/login','POST',{username:'espacos',password})).status,200);});
test('invalid password reset does not partially deactivate an account',async()=>{const env=fixture(),cookie=await login(env);const {user}=await (await req(env,'/api/admin/users','POST',{name:'Equipe',username:'equipe',password:'Senha-longa-2026',role:'ATENDIMENTO'},{Cookie:cookie})).json();assert.equal((await req(env,'/api/admin/users/'+user.id,'PATCH',{active:false,password:'curta'},{Cookie:cookie})).status,400);const result=await (await req(env,'/api/admin/users','GET',null,{Cookie:cookie})).json();assert.equal(result.users.find(u=>u.id===user.id).active,1);});
test('a login started before password reset cannot create a session with the old credential',async()=>{const env=fixture(),cookie=await login(env);const admin=(await (await req(env,'/api/admin/session','GET',null,{Cookie:cookie})).json()).user;const original=env.DB.prepare;let release,snapshot;const paused=new Promise(r=>snapshot=r),resume=new Promise(r=>release=r);let once=true;env.DB.prepare=(query)=>{const wrap=stmt=>({bind(...values){return wrap(stmt.bind(...values));},async first(){const row=await stmt.first();if(once&&query==='SELECT * FROM users WHERE username=?'){once=false;snapshot();await resume;}return row;},all:()=>stmt.all(),run:()=>stmt.run()});return wrap(original(query));};const oldLogin=req(env,'/api/login','POST',{username:'admin',password:env.ADMIN_PASSWORD});await paused;assert.equal((await req(env,'/api/admin/users/'+admin.id,'PATCH',{password:'Nova-senha-segura!2026'},{Cookie:cookie})).status,200);release();assert.equal((await oldLogin).status,401);assert.equal(env.DB.sql.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);});
